#
# This action keeps the master branch between the frePPLe private
# github repository and the public github repository.
#

name: Synchronize repositories

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checking out source code
        if: github.repository != 'frePPLe/frepple'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pushing to the public repository
        if: github.repository != 'frePPLe/frepple'
        # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
        run: |
          git remote add github-public https://token:${{ secrets.COMMUNITY_GITHUB_TOKEN }}@github.com/frePPLe/frepple.git
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push --set-upstream github-public master
